### ISSUE TITLE
Question 78 : Vol Paris-New York et neutralité carbonne

### ISSUE THREAD

**Issue by Marouann** [raphodn/know-your-planet#1]
Bonjour, bravo pour ce projet. J'ai cliqué sur une question au hasard et je crois que la bonne réponse indiqué est fausse.

Si chaque humain "a le droit" à 2100kg CO2 / an, alors il ne peut faire qu'un A/R Paris-New York. Donc la bonne réponse est la réponse b

https://github.com/raphodn/know-your-planet/blob/5a4020a4b88f9d4768950375ef4fc518853fd79a/api/questions/questions.yaml#L1549-L1568

**Comment by raphodn** [comment]
Salut Marouann, déjà merci d'avoir inauguré la séction Issues :)
Et en effet bien vu, je corrige ça !
