### ISSUE TITLE
Ajouter un filtre des quizs

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#120]
## Objectif

Pouvoir filtrer les quizs facilement

## Détails

Faire un rendu similaire aux filtres des questions. Donc à faire en même temps que https://github.com/raphodn/know-your-planet/issues/78

**Comment by bguivarch** [comment]
J'ai mergé les composants de filtres "questions" et "quiz".
On a donc le même filtres sur les quiz 
![image](https://user-images.githubusercontent.com/11310951/100484334-43a96980-30fc-11eb-8b1f-f914236cf072.png)


J'ai aussi repris ce que @raphodn avait fait pour filtrer les questions (et donc les quiz aussi) via l'url
`?author=Raphael%20Odini` par exemple

**Comment by raphodn** [comment]
du coup je ferme 👏 
la v2 des filtres ça se passera ici https://github.com/raphodn/know-your-planet/issues/78
