### ISSUE TITLE
Eviter le flicker quand on va directement à une page de l'application

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#166]
## Objectif

Rendre la navigation plus rapide et agréable pour l'utilisateur

## Détails

Si je vais directement sur la page d'un quiz (un lien qu'on m'a partagé par exemple), l'application va charger, afficher très rapidement la Home Page ("flicker"), puis arrive à la bonne page. Il faudrait arriver directement à la bonne page :)

https://streamable.com/o85el9

**Comment by lodi-g** [comment]
Pour info, le bug n'est reproductible chez moi que avec le build de production et pas de développement, même avec du network/cpu throttling.

**Comment by raphodn** [comment]
Idem, et la HomePage ne me semble pas 'mounted()' donc je n'ai pas d'explications ni de pistes de solutions 😕

**Comment by lodi-g** [comment]
Je m'y assigne, mais si quelqu'un a des idées je suis preneur :)

**Comment by lodi-g** [comment]
J'ai creusé un peu, et le problème vient du `PrerenderSpaPlugin` qui est trigger lorsqu'on fait un build de production.

En effet, il va prerender la homepage dans l'index.html de production. Ensuite, Vue va afficher ce qu'il y a dans le HTML par défaut pendant son chargement. Une fois chargé, il prends la main et vire la homepage pour mettre la page du quizz.

Solution simple: virer le plugin, mais pas cool car ça dégrade la performance de la homepage. 
Autre solutions: ... ? Des idées ?

**Comment by raphodn** [comment]
Top d'avoir trouvé la source du problème !
Quand j'ai utilisé ce plugin, je souhaitais avoir du contenu crawlable et pas juste un <app></app>. Mais ca provoque quand même un comportement désagréable.
Ca serait en effet interessant de prerender un lot de pages additionnelles. Par contre prendre la dernière id n'est pas fiable, car il y a eu pas de quizs supprimés on dirait, les id ne se suivent pas. Et surtout on pourrait à terme changer l'url pour y mettre le slug du quiz. Lors du prerender on peut aller chercher tous les ids existants sinon ? Ca serait interessant de tester, et avec Netlify on a les review app donc on pourrait tester avant de merger (à condition que ça ait le même comportement qu'en prod ^^)

**Comment by lodi-g** [comment]
Ah, je n'avais pas vu ta réponse. La MR que je propose fixe le problème. 
J'ai essayé de prerender une page de quizz et je ne sais pas pourquoi mais ça n'avait pas l'air de fonctionner. Je n'ai pas non plus tryhard :D.

On peut éventuellement clore cette tâche si ma MR te convient et élargir le scope du prerendering dans l'issue liée aux performances ou dans une autre ? 

Et aussi il y a la CLI netlify (que j'ai découvert aujourd'hui), très pratique pour tester ce genre de trucs.
