### ISSUE TITLE
Revoir en profondeur la gestion des stats

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#32]
## Objectifs

Avoir une gestion des stats qui soient stables, scalables, claires et utiles 📊 

## Détails

Heroku Postgres nous limite à 10,000 rows. Donc soit on stock les stats à un autre endroit, soit on les stock de façon plus intelligente.

Proposition:
1. Quelles stats ?
  - Avoir des stats journalière (1 row par jour, JSONField). metrics: nombre de réponses totales, par heure, par page, etc
  - Avoir des stats par question (1 row par question, JSONField). metrics: nombre de réponses totales, par choix de réponse
  - Futur: Avoir des stats par quizz, like/dislike, ...
2. Comment les processer
  - cron job toutes les semaines (tous les jours ?) qui prend les stats dans la db, les processent (aggregation par jour et update par question), et suppriment les rows pour faire de la place
3. Les afficher
  - Etre capable de récuperer les stats d'une question en temps réel pour l'afficher en dessous de la réponse
  - Connecter un dashboard ([Superset](https://superset.incubator.apache.org/) 😃) pour monitorer les metrics (réajuster la difficulté des questions, voir la réaction et le feedback des gens, etc)

**Comment by louisguitton** [comment]
Super d'avoir ouvert une RFC 👏 
Tu rentres dans le domaine des `analytics` et du `data engineering`. Comme pour beaucoup de projets, ces deux domaines ne sont pas le coeur du projet, et c'est important de bien architect le truc pour pas avoir à y passer trop de temps, vu que ce n'est pas **core**. Ravi d'apporter mon point de vue du coup.

## Architecture en temps normal

En temps normal (= si ressources infinies), du séparerais tes DBs. Tu aurais ta Postgres pour la webapp `prod DB` et ta Postgres pour les analytics `data warehouse (DWH)`. Quand tu scales, la DWH tu peux utiliser Redshift etc ... Mais en l'occurence, Postgres pour une DWH c'est très bien au début.

> 1) Quelles stats ?

En temps normal, tu ferais tes aggregations dans la DWH en utilisant SQL. Il y a toute une façon d'organiser ta DWH et de gérer ta codebase SQL pour que ça reste propre, mais en clair: ça marche très bien, et beaucoup mieux que si tu commençais à coder ça en python avec ton ORM. 
Rapide overview de la structure d'une DWH (on top of each other):
- raw_events tables
- staging models: où tu clean tes events (renaming et denormalisation)
- dimension tables and fact tables : où tu calcules tes aggregates
- visualisation models : les queries que tu écrirais dans Superset, mais au lieu de les écrires dans Superset, tu crées des tables dans ta DWH, et ton query Superset devient `select * from ...` come ça tu source control tout ça

## Architecture préconisée dans ton cas

Là dessus tu as un double problème de pricing d'après ce que je comprends:

1. tu as le droit que à 1 DB
1. tu as le droit que à 10k rows

Donc l'architecture que je préconise est la suivante:

- garder DWH and prod DB dans la même Postgres instance
- compute aggregate `in core` using SQL : staging models, fact tables, viz models (ce qui mettra à jour Superset automatiquement
- periodically `UNLOAD` tes event tables vers S3 (y'a une free tier dessus, et de toute façon même si c'est payant, je te conseille pas de jeter à la poubelle des datas, autant payer 1€ par mois pour garder l'historique)
- periodically compute compute aggregates `out of core` to double check or update old aggregates in case of late arrival of events = pas dans la DWH en SQL vu que tu n'auras plus les raw_events tables. A la place je te conseille de faire ça en pandas/dask directement en téléchargeant les données de S3 ; puis de upsert dans ta DWH avec pandas.to_sql(if_exist=replace)

Le dernier point prend en charge tes questions dans ton point 3
> 3) Les afficher

Par contre dezo pas de temps réel aha, sinon il te faut un autre niveau de setup lol.

##  Scheduling

> 2) Comment les processer

Effectivement un cronjob c'est ce qu'il te faut. Ou plutôt 2:
1. cronjob to free space in DB (UNLOAD raw_events table to S3): can happen once a week or once a month I guess 
1. cronjob to run your models (staging models, fact tables, viz tables): need to happen once an hour if you want fresh stats

Le moins t'auras à gérer de cronjobs, le mieux tu seras. (si tu les mets sur ton server, tu n'auras pas d'alerting etc...)
Du coup pour le cronjob 1 je te conseille [prefect cloud](https://www.prefect.io/) et pour le cronjob 2 je te conseille [dbt cloud](https://www.getdbt.com/). Tous les deux sont des librairies python très stylées et à la pointe du data engineering; les deux services ont une free tier et en gros te schedulent tes jobs pour toi, avec une nice UI, des notifications etc...
La learning curve pour ces deux tools n'est pas aussi steep que ça en a l'air, et je peux te guider (et te setup le truc très rapidement si t'es bloqué).

## Day to day life with my achitecture

- ta codebase github maintenant comporte 3 services: le backend, le prefect job pour unload, les dbt models pour ta DWH
- https://cloud.prefect.io/ te run ton cronjob 1 toutes les semaines ou tous les jours si tu veux
- https://cloud.getdbt.com/ to run ton cronjob 2 toutes les heures
- tu gardes ta DB gratos sur Heroku
- tes dashboard Superset ont une 1-hour latency
- tu peux utiliser dans le backend tes aggregations (fact tables) sans problèmes; elles aussi ont une 1-hour latency

**Comment by louisguitton** [comment]
PS (non des moindres): je t'ai codé vite fait les modèles pour tes events. Et je t'ai mis le tout dans une DB sqlite.
https://drive.google.com/open?id=1LC2sq2A26J105q4USecZ3Z8x7i5FUNuf
```sh
pip install litecli
litecli dwh_raph.db
dwh_raph.db> .tables
```

**Comment by raphodn** [comment]
Wow merci pour tout ça Louis :)

quelques points que tu mentionnes et auquels j'avais pas pensé:
- ne pas jeter à la poubelle les datas, les garder sur S3 (par exemple)
- séparer les cronjobs en deux tâches distinctes
- avoir un outil pour monitorer les cronjobs
- "periodically compute compute aggregates out of core to double check or update old aggregates in case of late arrival of events" 👀

Après sur l'implementation il se peut que je me tourne vers les addons Heroku pour simplifier le tout et ne pas éparpiller trop le mgmt de l'app / avoir des services web additionnels.
Heroku a un [Scheduler](https://elements.heroku.com/addons/scheduler) par exemple, ou encore plus simple le [clock process](https://devcenter.heroku.com/articles/clock-processes-python), et parmi [tous les addons](https://elements.heroku.com/addons) il y en a certains qui pourraient faire le monitoring aussi.

**Comment by raphodn** [comment]
Modif récente [ici](https://github.com/raphodn/know-your-planet/commit/aaea4a20045719741e3b2c9e444b993d3b721ee8) : séparé les stats des Questions dans un modèle dédié `QuestionAggStat`
- pour ne pas avoir les stats lors de l'export des Questions
- pour avoir le backend comme "stat repository" et dans le frontend sourcer les questions depuis le yaml

**Comment by raphodn** [comment]
Je ferme l'issue pour cleaner un peu.

Actuellement il y a une management command `generate_daily_stats` qui : 
1. prend toutes les nouvelles entrées de `QuestionAnswerEvent` & `QuestionFeedbackEvent`
2. met à jour les `QuestionAggStat` concernés
3. créés (ou met à jour) les `DailyStat`
4. supprime  toutes les entrées de `QuestionAnswerEvent` & `QuestionFeedbackEvent`

Cette commande peut être lancé dans l'admin, grâce à un bouton dans la section `DailyStat`.

Des stats sont aussi affichés dans différentes pages de l'admin (avec des filtres possibles).

Il manque la gestion des stats des quizs `QuizAnswerEvent` & `QuizFeedbackEvent`. Si c'est possible, car l'on ne veut pas perdre en chemin : 
- le résultat du quiz
- l'évolution du nombre de réponse à un quiz donné au cours du temps
