### ISSUE TITLE
Trouver un nom de domaine

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#41]
## Objectif

Avoir un meilleur nom de domaine, ne plus avoir netlify dans l'url

## Détails

Nom de domaine actuel:
https://know-your-planet.netlify.app

Idées vrac:
- know-your.planet
- quiz-planet.eco / quiz-planete.eco
-

**Comment by PYLager** [comment]
Je met les propositions de noms évoquées sur le discord : 
- Planète en questions
- s'quiz the planet
- Quiz no good
- Hubrisq'

**Comment by IPv777** [comment]
cette issue peut être fermée je suppose ?

-> #124

**Comment by raphodn** [comment]
En effet, je ferme :)

Petit historique pour la postérité : 
- Mars 2020 : Know Your Planet / https://know-your-planet.netlify.app/
- Sept 2020 : Quiz ta Planète / quiztaplanete.fr
- Nov 2020 : Quiz de l'Anthropocène / quizanthropocene.fr
