### ISSUE TITLE
Mettre en valeur les associations proche du projet

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#51]
## Objectif

Dans la page "A propos", afficher plus clairement les différentes assos qui aident de près ou de loin au projet.

## Détails

- Assos : logos, section plus grosse sur la page, liens vers les quizs correspondants (via un tag)
- Projets / Jeux similaires
- page de coût / dons

## Page actuelle

![screenshot-know-your-planet netlify app-2020 05 27-15_01_39](https://user-images.githubusercontent.com/7147385/83021952-1388ed00-a02b-11ea-9d75-e75573b4f25a.png)

**Comment by PYLager** [comment]
J'ai demandé à CPLC ils sont ok pour afficher leur logo et une phrase du genre "Contenu réalisé en partenariat avec xxx"

**Comment by raphodn** [comment]
en plus de mettre en valeur des assos, je pensais pointer vers quelques projets/jeux similaires
