### ISSUE TITLE
Pouvoir afficher des questions à choix multiples

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#52]
## Objectif

Gérer des questions avec 2, 3 ou 4 réponses. Pour l'instant les questions ont une seule réponse possible. 

## Détails

- pouvoir stocker plusieurs réponses dans le champs `answer_correct`
- une bonne réponse est si (et seulement si) toutes les réponses ont été selectionnés ?
- ~rajouter un champs `has_multiple_answers`~ rajouter un type 'QCM réponse multiple'
- rajouter un petit message `plusieurs réponses attendues`
- changer les radio buttons en checkbox
- quid des questions avec plusieurs réponses 'possibles' ? cas à traiter à part ?

ping @PYLager

**Comment by PYLager** [comment]
Pas forcément besoin de champ has_multiple_answer, on pourrait utiliser le champ type, et splitter la valeur QCM en deux : `QCM_choix_unique` et QCM_choix_multiple

**Comment by raphodn** [comment]
j'aime bien ton idée de mettre l'information dans le `type` ! t'as une question qu'on pourrait essayer ?

**Comment by PYLager** [comment]
Oui la #438
https://www.notion.so/quizplanete/La-Chine-est-le-premier-metteur-de-GES-au-monde-donner-au-moins-3-explications-0e01e45dd10242bdac6cb74f215e447a

Je l’ai laissé en très brouillon vu que la fonctionnalité n’existe pas.

Je suis en train de suivre le MOOC de Michael Mann sur le climat, et il en a fait pas mal de questions à choix multiples comme ça.

**Comment by raphodn** [comment]
On peut avoir:
- `QCM` : 1 seule réponse. par exemple `answer_correct: a`
- `QCM-RM` (Réponse Multiple) : 2, 3 ou 4 réponses. par exemple `answer_correct: bc`

**Comment by raphodn** [comment]
- [x] Data : nouveau type de Question `QCM-RM`
- [x] Backend : gérer les différentes options pour `answer_correct`, avec une couche de validation dans le modèle Question
- [ ] Frontend : gérer l'affichage des questions à choix multiple (message d'info "plusieurs réponses", correction, ...)
