### ISSUE TITLE
Proposer un indice pour faire réfléchir l’utilisateur

### ISSUE THREAD

**Issue by PYLager** [raphodn/know-your-planet#53]
Bouton "donne moi un indice" au dessus du bouton valider.

L’indice serait à renseigner pour idéalement chaque question, et devrait permettre à l’utilisateur de faire des déductions pour deviner la réponse (exemple d’indice : remettre en contexte, donner un ordre de grandeur, ...)

**Comment by raphodn** [comment]
j'ai rajouté une colonne ~`question_hint`~ `indice` dans le Notion. j'hésite au passage à passer toutes les variables en français ça aiderait à la compréhension des champs

**Comment by PYLager** [comment]
L'anglais me va bien c'est habituel et ça évite les accents ! ^^
