### ISSUE TITLE
Aligner les choix des réponses (et les liens hypertextes)

### ISSUE THREAD

**Issue by PYLager** [raphodn/know-your-planet#54]
Les choix de réponses sont centrés, lorsque les réponses font à peu près la même longueur c’est bien, mais si c’est trop différent ça fait tout moche et c’est pas agréable à lire.

Idéalement aligner les réponses à gauche, tout en gardant un décalage par rapport à la question (ou centrer le bloc des réponses).

Les liens hypertextes sont centrés aussi, il serait plus agréable de les aligner à gauche.

**Comment by raphodn** [comment]
Je joins deux screenshot de la même question (un au format "mobile", l'autre "desktop").
On alignerait tout à gauche ? je suis d'accord que centré c'est bof comme rendu, mais il faudrait trouver un entre-deux :)

![screenshot-know-your-planet netlify app-2020 06 05-16_54_22](https://user-images.githubusercontent.com/7147385/83891492-8857d780-a74d-11ea-8961-2521b7536efe.png)

![screenshot-know-your-planet netlify app-2020 06 05-16_54_21](https://user-images.githubusercontent.com/7147385/83891478-8261f680-a74d-11ea-8ac5-c63e5f1121f6.png)

**Comment by PYLager** [comment]
Le mieux serait d’aligner les réponses à gauche dans un bloc, et de centrer ce bloc :)

**Comment by raphodn** [comment]
premier test en mettant un `max-width: 500px` et `text-align: left`
on peut ajuster sur le `max-width` pour centrer d'avantage

![Screenshot 2020-06-09 at 18 02 07](https://user-images.githubusercontent.com/7147385/84171732-7347b500-aa7b-11ea-97c6-f2705e071f73.png)
![Screenshot 2020-06-09 at 18 02 15](https://user-images.githubusercontent.com/7147385/84171736-7478e200-aa7b-11ea-9e8f-511943e2536d.png)
![Screenshot 2020-06-09 at 18 02 22](https://user-images.githubusercontent.com/7147385/84171741-75117880-aa7b-11ea-881b-a3a0539fd4a4.png)
![Screenshot 2020-06-09 at 18 02 34](https://user-images.githubusercontent.com/7147385/84171745-75aa0f00-aa7b-11ea-8090-03f0a9282cd0.png)

**Comment by PYLager** [comment]
Hmm pour la version mobile ça va, mais pour le desktop c’est pas fou je trouve... dans ma tête j’imaginais que ça allait rendre autrement.

Est-ce qu’il y a moyen de :
- contraindre le cadre complet de la question en largeur (800px ?)
- Aligner le bloc des questions à gauche, avec un léger décalage (100-200px ?)

Pour qu’à chaque fois que l’utilisateur clique sur valider, la position des réponses reste fixe.

**Comment by raphodn** [comment]
Une autre version avec la même question et différentes tailles d'écran

![Screenshot 2020-06-15 at 19 12 53](https://user-images.githubusercontent.com/7147385/84686475-49d7cf00-af3c-11ea-914d-12d1cbfc3d51.png)
![Screenshot 2020-06-15 at 19 12 59](https://user-images.githubusercontent.com/7147385/84686477-4b08fc00-af3c-11ea-8edc-bfb4467993f9.png)
![Screenshot 2020-06-15 at 19 13 05](https://user-images.githubusercontent.com/7147385/84686478-4ba19280-af3c-11ea-9ba6-ea02eda5f8be.png)

**Comment by PYLager** [comment]
Ah c'est bien ! Ça fait propre je trouve :)
Pour moi c'est ok, merci !

**Comment by raphodn** [comment]
les modifs sont ici https://github.com/raphodn/know-your-planet/pull/60
merci ! je suis en train de voir pour avoir netlify qui nous donne une url 'temporaire' pour pouvoir tester et faire des retours avant de merger le code
