### ISSUE TITLE
Autoriser les sauts de lignes dans les questions

### ISSUE THREAD

**Issue by PYLager** [raphodn/know-your-planet#55]
Tout est dit :)

Et dans les réponses aussi (moins gênant je trouve).

**Comment by raphodn** [comment]
j'aurais pensé que c'était l'inverse ^^
- moins gênant pour la question, qui est souvent courte
- utile pour les réponses comme certaines des tiennes qui sont sur plusieurs lignes/bullet points

Normalement il n'y a pas de problème de stocker des sauts de ligne. Il faut que je comprenne où ça coince. J'avais eu des soucis au moment de l'import de ton excel dans Notion de mémoire. mais ensuite de Notion à l'application web ça devrait aller. je vais faire quelques tests

**Comment by raphodn** [comment]
bon Notion semble être compliqué avec cette colonne 'title', ils n'autorisent pas de passage à la ligne.. il y a peut-etre moyen d'inverser les colonnes text & id par exemple.

https://www.notion.so/Tables-66a1cce8fb6f4f64b9996f4146c51fad#9ff932130da94b149f5227bb433efafe
https://twitter.com/NotionHQ/status/1118311662379913216

**Comment by PYLager** [comment]
C’est juste pour la question alors du coup ?
Et si on met un caractère spécial tu peux le transformer ? Une fabulation par exemple, ou un pipe ?

**Comment by raphodn** [comment]
j'ai passé du temps ce matin sur l'export de Notion, du coup ca conserve bien les sauts de ligne finalement. Et j'ai fait une modif pour l'avoir dans l'interface aussi (pour l'instant seulement au niveau de `answer_explanation`. Ca ressemblerait à ça par exemple : 

![Screenshot 2020-06-24 at 13 45 33](https://user-images.githubusercontent.com/7147385/85550231-0c043600-b621-11ea-85da-89b40aa798b9.png)

**Comment by raphodn** [comment]
- c'est bon pour les Questions : champs `text` & `answer_explanation`
- pour les quizs (`introduction` & `conclusion`) ca se passe ici https://github.com/raphodn/know-your-planet/issues/151
