### ISSUE TITLE
💡 Un mode challenge / quizz

### ISSUE THREAD

**Issue by laem** [raphodn/know-your-planet#6]
Une sélection de 10 ou 20 questions avec un score très visible, que l'on peut partager à des amis pour tester ses connaissances.

Un peu de compétition 😄 

Et puis dans l'état actuel, ça laisse un [sentiment un peu frustrant quand je quitte le site](https://fr.wikipedia.org/wiki/Fear_of_missing_out).

**Comment by raphodn** [comment]
Salut Mael !
Merci de venir participer et de proposer de nouvelles fonctionnalités :)
Le mode quizz est dans la todo pour ce weekend justement. Il faut que je curate 10 questions pour commencer, et tester un premier workflow.

En règle général il y a 2 options pour ce genre d'usage:
1) l'utilisateur sait qu'il répond à 10 questions (genre `X/10` d'affiché) mais les questions sont affichées sur des pages distinctes, avec la réponse tout de suite
2) l'utilisateur répond aux 10 questions sur la même page, avec 1 seul bouton Valider, et le score + résultats ensuite

Je n'ai pas encore décidé qu'elle option choisir

**Comment by raphodn** [comment]
première version du workflow quiz (c'est pas finalisé, juste pour donner une idée) 👇 
> https://streamable.com/23qgot

**Comment by laem** [comment]
Génial

**Comment by laem** [comment]
Vos résultats: 8 / 10 :)
