### ISSUE TITLE
Expliquer les accronymes (glossaire)

### ISSUE THREAD

**Issue by PYLager** [raphodn/know-your-planet#64]
Question de Matthieu :
« on utilise souvent des termes techniques ou acronymes. Par ex : CO2 éqv. Pas moyen de faire un lien hypertexte sur ces expressions depuis la question ou la réponse vers une explication, un glossaire, comme je viens de le faire dans ce message avec CO2 éqv ? »

**Comment by raphodn** [comment]
Super idée :)
en HTML il y a le tag `<abbr>` qui permet d'avoir ce comportement. Le 'challenge sera d'avoir un glossaire, et d'avoir ces acronymes détectées et expliquées à partir du glossaire.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

<img width="311" alt="Screenshot 2020-06-16 at 16 04 04" src="https://user-images.githubusercontent.com/7147385/84785070-549d6d00-afeb-11ea-8d27-309c9c75ba75.png">

**Comment by raphodn** [comment]
donc par chaque élément du glossaire on aurait:
- l'abréviation
- une liste d'autres versions possibles de cette abréviation
- la définition minimale de l'abréviation (ce qui est affichée quand on passe la souris dessus)
- une explication plus détaillée
- un lien pour en savoir plus ?

exemple: 
- `CO2e`
- eqCO2, éq. CO2, CO2e ou CO2-eq
- équivalent CO2
- L'équivalent CO2 est, pour un gaz à effet de serre, la quantité de dioxyde de carbone (CO2) qui provoquerait le même forçage radiatif que ce gaz, c'est-à-dire qui aurait la même capacité à retenir le rayonnement solaire. Dans le cas d’un mélange de GES, l’émission en équivalent CO2 est obtenue en additionnant les émissions en équivalent CO2 de chacun des gaz.
- https://fr.wikipedia.org/wiki/%C3%89quivalent_CO2

**Comment by raphodn** [comment]
Implémentation technique : dans le frontend, sur certains blocs de textes, avoir un une méthode pour parcourir le texte, matcher avec le glossaire, et ajouter des tags `<abbr>` autour
- jquery plugin [autoabbr.js](https://github.com/pauljz/autoabbr)
- regex example : [ici](https://stackoverflow.com/questions/10017684/how-can-i-add-pop-up-tooltip-definitions-to-words-on-a-webpage-when-hovered) and [ici](https://stackoverflow.com/questions/29082101/js-regex-to-match-a-string-within-html-tags-that-arent-a)
- vuejs filter similaire https://stackoverflow.com/questions/49852480/adding-html-in-vue-js-using-data-filters

**Comment by raphodn** [comment]
Reste à faire : 
- [ ] prendre en compte les noms alternatifs des éléments dans le glossaire
- [ ] pointer vers la définition longue ?
- [ ] prendre en compte les cas particuliers lors du str.replace() (éviter les detection aux seins d'autres mots ? )
