### ISSUE TITLE
Question "Laquelle de ces activités permet de réduire le plus son empreinte carbone ?"

### ISSUE THREAD

**Issue by laem** [raphodn/know-your-planet#7]
Pas évident de retrouver la réponse dans la référence citée et l'image.

**Comment by raphodn** [comment]
J'avoue que je ne suis pas fan de l'image, mais c'est une question/sujet un peu touchy faudrait voir pour l'améliorer en effet

**Comment by raphodn** [comment]
on a fait quelques modifs sur la question depuis
