### ISSUE TITLE
Difficulté moyenne d'un quiz

### ISSUE THREAD

**Issue by Sarma38** [raphodn/know-your-planet#73]
Pour celui que j'ai créé, la difficulté moyenne apparaît avec 10 nombres après la virgule ! Réduire à 1 seule décimale.

**Comment by raphodn** [comment]
Salut Matthieu, j'ai vu ca en effet quand t'as créé le quiz. Normalement c'est réparé (cf image), tu le vois toujours apparaitre de ton coté ? Il y a ensuite la gestion de l'image qui pose un peu problème, il faudrait définir un ratio d'image conseillé

![Screenshot 2020-06-28 at 22 21 10](https://user-images.githubusercontent.com/7147385/85957439-cd0e1180-b98d-11ea-9096-878a91c07ca7.png)

**Comment by Sarma38** [comment]
top, parfait.
