### ISSUE TITLE
Question "km² désertifiés"

### ISSUE THREAD

**Issue by laem** [raphodn/know-your-planet#8]
Cette question m'a laissé perplexe, car je n'ai aucune surface de cette taille en tête. 

https://github.com/raphodn/know-your-planet/blob/master/api/data/questions.yaml#L1077-L1095

**Comment by raphodn** [comment]
Elle a été légèrement modifiée !
https://github.com/raphodn/know-your-planet/commit/208e743aa1b4b914455f36ab67bcf06ee039f446#diff-5b15e67104885116283c60d6fe739548R1179
