### ISSUE TITLE
à l'issue d'un quiz, faire un récap des questions trouvées juste (en vert par ex) et des fausses

### ISSUE THREAD

**Issue by Sarma38** [raphodn/know-your-planet#84]
plutôt qu'une seule stat.

**Comment by raphodn** [comment]
C'est déjà possible en fait, quoique *largement améliorable*
- sur la 1e image, quand tu cliques sur "Afficher les questions"
- ca affiche les cartes des questions avec un jeu de couleur

Image 1
![Screenshot 2020-08-04 at 22 57 41](https://user-images.githubusercontent.com/7147385/89344346-07ae4c80-d6a6-11ea-9406-c2d941416164.png)
Image 2
![Screenshot 2020-08-04 at 22 57 51](https://user-images.githubusercontent.com/7147385/89344348-08df7980-d6a6-11ea-9e65-581ee23789ed.png)

**Comment by Sarma38** [comment]
en effet, c'est très bien comme cela.
