### ISSUE TITLE
Fournir un lien pour partager le quiz (facebook twitter etc...).

### ISSUE THREAD

**Issue by Sarma38** [raphodn/know-your-planet#85]
Ca pourrait booster notre visibilité

**Comment by raphodn** [comment]
Pour l'instant j'ai rajouté rapidement un bandeau avec le lien du quiz à copier-coller.
Mais on peut étoffer :)

![Screenshot 2020-08-06 at 15 31 05](https://user-images.githubusercontent.com/7147385/89537622-e2caee00-d7f9-11ea-9b0a-38c554a2cfd6.png)

**Comment by Sarma38** [comment]
C'est bien. Tant qu'on est là-dessus, une autre idée d'amélioration m'est venue : prévoir un champ texte (et hypertexte) à l'issue d'un quiz, pour qu'on puisse faire une conclusion et surtout orienter vers autre chose : des lectures, des assos, des moyens de se bouger....On a ça dans la page 'à propos', mais là ça serait plus ciblée.
Et aussi, dans la page à propos : faire un mini-portrait de toi, PY et moi, ça incarnerait la chose !

**Comment by raphodn** [comment]
d'acc du coup pour les quizs je viens de : 
- renommer le champ `description` en `introduction`
- créer le champ `conclusion`

Tu peux remplir le nouveau champ dans l'admin. Et il faut encore que je l'affiche quelque part dans l'interface (surement juste en dessous de "Votre résultat")
