### ISSUE TITLE
Une fois qu'on a cliqué sur un like/dislike, faire apparaître les stats pour cette question (ex : 4 likes, 1 dislike)

### ISSUE THREAD

**Issue by Sarma38** [raphodn/know-your-planet#86]

**Comment by raphodn** [comment]
bonne idée 👍   je viens de rajouter la fonctionnalité

![Screenshot 2020-08-06 at 16 00 05](https://user-images.githubusercontent.com/7147385/89543639-7653ed00-d801-11ea-8f49-794f0e21e6b6.png)

**Comment by Sarma38** [comment]
Super ! Mais je viens de tester sur 2-3 questions, et ça ne marchait pas. Tu attends une prochaine release j'imagine ?

**Comment by raphodn** [comment]
Non ca devrait être accessible, la raison est qu'il faut que tu rafraichisse l'application (en gros au lancement de l'application le telephone/ordi va chercher tout le code, et ne le redemande plus ensuite, même quand on navigue d'une page à une autre)

**Comment by Sarma38** [comment]
en effet, merci
